### ISSUE TITLE
Crashes on start with Abort trap: 6

### ISSUE THREAD

**Issue by kije** [luke-jr/bfgminer#273] opened 2013-09-03 22:11 UTC
Crashes on start with error Abort trap: 6

On:
Mac OS X 10.8.4
Installed via homebrew and brew tap nwoolls/xgminer

**Comment by arjunyg** [comment] 2013-10-22 00:27
Same deal here:
Mac OS X 10.7.5
Compiled with some self-built packages, some installed through fink and some through macports.
Debug/Verbose output shows nothing.

**Comment by luke-jr** [comment] 2013-10-22 00:45
Version?

**Comment by arjunyg** [comment] 2013-10-22 01:20
3.3.0
lol that's fairly important, can't believe I left that out.

**Comment by luke-jr** [comment] 2013-10-22 01:29
Will probably need a backtrace to get any further on this.

**Comment by arjunyg** [comment] 2013-10-22 04:54
Yeah I thought so, but I'm not terribly familiar with autoconf myself, so if you could tell me how to get debug symbols for the gdb, I could get you a stack trace.
Actually I might be able to patch it myself, but I'll probably need a fair bit of time to get than done, as I have a pretty busy schedule.

**Comment by luke-jr** [comment] 2013-10-22 05:22
```
./configure CFLAGS='-O0 -ggdb' && make clean && make
```

**Comment by geeeoff** [comment] 2013-12-17 03:10
I just compiled from 3.8.1 source on OSX 10.8.5 and was having the same/similar issue:

[2013-12-16 20:01:57] Waiting for devices; press 'M+' to add, or 'Q' to quitAbort trap: 6

When I added in your CFLAGS='-O0 -ggdb' and recompiled the application launched fine - no error like above.

Haven't started really using it yet but did a test connect to eligius and it came up fine.

Let me know if you want me to produce any debugging info

**Comment by luke-jr** [comment] 2013-12-17 03:26
Hmm, try with -O1 -ggdb then. If that still fails to reproduce it, -O2 -ggdb

**Comment by geeeoff** [comment] 2013-12-17 03:39
-O1 -ggdb caused:

[2013-12-16 20:37:36] Waiting for devices; press 'M+' to add, or 'Q' to quitAbort trap: 6

Is there a dump file or something you want me to send over?

**Comment by luke-jr** [comment] 2013-12-17 05:18
run it with:

```
gdb <your bfgminer command here>
```

then when it crashes, you'll get a gdb prompt; run:

```
bt
```

**Comment by geeeoff** [comment] 2013-12-18 04:57
Tried using -O1 and -O2 both result in a crash like noted above but when I run gbd for either I get the following:

sh-3.2# gdb bfgminer
GNU gdb 6.3.50-20050815 (Apple version gdb-1824) (Wed Feb  6 22:51:23 UTC 2013)
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin"...Reading symbols for shared libraries ........ done

(gdb) bt
No stack.

**Comment by luke-jr** [comment] 2013-12-18 05:02
You need to run it in gdb. I guess my instructions may have been confusing...

```
gdb <your bfgminer command here>
run
```

**Comment by geeeoff** [comment] 2013-12-18 05:13
Ah, got it - obviously, I am no C developer so it has been a lesson in C debugging, thanks I actually appreciate it ...  Here's the stack - this is with the -O2 compile:

[2013-12-17 22:11:00] Waiting for devices; press 'M+' to add, or 'Q' to quit
Program received signal SIGABRT, Aborted.
0x00007fff90a86212 in __pthread_kill ()
(gdb) bt
#0  0x00007fff90a86212 in __pthread_kill ()
#1  0x00007fff8fa5ab24 in pthread_kill ()
#2  0x00007fff8fa9f031 in __abort ()
#3  0x00007fff8fa9ff97 in __stack_chk_fail ()
#4  0x000000010000793f in _wlog (str=<value temporarily unavailable, due to optimizations>) at miner.c:3840
#5  0x00000001000079c9 in _log_curses_only (prio=3595, datetime=0x7fff5fbaa308 "$????", str=0x7fff77a66278 "") at miner.c:3861
#6  0x000000010003b701 in _my_log_curses [inlined]() at /root/bfgminer-3.8.1/logging.c:33
#7  0x000000010003b701 in _applog (prio=5, str=0x7fff5fbb89f8 "Probing for an alive pool") at logging.c:95
#8  0x0000000100020d12 in main (argc=1, argv=0x7fff5fbffb70) at miner.c:11292
(gdb)

**Comment by arjunyg** [comment] 2013-12-18 05:22
A few humble remarks:
If this crash is a result of optimizations made by the compiler, might it make sense to file a bug report with the developers of the compiler and/or test different compilers? Most likely, there is nothing we can do about some arcane optimization that is incorrect.

I could be entirely wrong, considering I am not experienced with the inner workings of compilers, but there are my two cents, I guess.

-Arjun

**Comment by geeeoff** [comment] 2013-12-18 05:28
I'll defer to luke-jr for his thoughts since I didn't see any usable debug info provided up until this point.

I guess.

**Comment by luke-jr** [comment] 2013-12-18 05:43
@arjunyg I've seen cases where optimisations revealed real bugs before; for example, GCC decided to remove a constant completely simply because it went out of scope before it was really used. __stack_chk_fail suggests there is stack corruption, and checks for that are only enabled with optimisations. So I'm definitely going to look very closely at this one...

**Comment by luke-jr** [comment] 2013-12-18 05:46
Yep, I see a likely stack corruption bug. @geeeoff please test http://codepad.org/rPhu5l5C

**Comment by arjunyg** [comment] 2013-12-18 05:46
Interesting, this sure looks like a pain to debug. Good luck ;)

**Comment by luke-jr** [comment] 2013-12-18 05:52
Sorry, please test http://codepad.org/7TeSoqN3 @geeeoff

**Comment by geeeoff** [comment] 2013-12-18 06:02
This has fixed the issue and bfg came up after a normal compile without the error previously reported.  Thanks for taking care of this.

**Comment by luke-jr** [comment] 2013-12-18 06:04
Great, fixed in bb7bd7673 then. :)

**Closed as completed by luke-jr** 2013-12-18 06:04 UTC

**Comment by arjunyg** [comment] 2013-12-18 06:14
Wow that was quick! Good job guys and thanks for that fix, now I can run this on my Mac :)

**Comment by geeeoff** [comment] 2013-12-18 06:20
all @luke-jr - definitely a deadly developer - I was just getting schooled in the basic points of C debugging ... but if you aren't learning, well you know what they say ...
