### ISSUE TITLE
Segmentation fault if failover fails....

### ISSUE THREAD

**Issue by MaStr** [luke-jr/bfgminer#237] opened 2013-06-05 04:23 UTC
Hi,
my bfgminer 3.0.1 got a seg. fault yesterday night, during a not working failover. Don't know why this network issues occured, but the daily disconnect is around 03:00
Yes, my network is currently not setuped for IPv6 

my Sysog output:

Jun  5 00:07:16 pucky bfgminer[32632]: Stratum from pool 0 requested work update
Jun  5 00:07:32 pucky bfgminer[32632]: Accepted d2446f8a ZTX 0  pool 0 Diff 1/1
Jun  5 00:07:35 pucky bfgminer[32632]: Stratum connection to pool 0 interrupted
Jun  5 00:07:35 pucky bfgminer[32632]: Closing socket for stratum pool 0
Jun  5 00:07:35 pucky bfgminer[32632]: Testing pool http://mint.bitminter.com:8332
Jun  5 00:07:36 pucky bfgminer[32632]: Stratum authorisation success for pool 1
Jun  5 00:07:37 pucky bfgminer[32632]: Unknown stratum msg: {"result":null,"error":[20,"Unknown method",null],"id":"txlist1377-da"}
Jun  5 00:07:37 pucky bfgminer[32632]: Stratum connect failed to pool 0: Failed to connect to 2a01:4f8:130:2006::2: Network is unreachable
Jun  5 00:07:37 pucky bfgminer[32632]: Pool 0 http://eu.triplemining.com:8344 not responding!
Jun  5 00:07:37 pucky bfgminer[32632]: Switching to pool 1 http://mint.bitminter.com:8332
Jun  5 00:07:37 pucky bfgminer[32632]: Closing socket for stratum pool 1

My BFGMiner-Startup paramters:
bfgminer  --retries 3  --api-allow 192.168.56.0/24 --api-description "pucky" --api-listen --api-network   -Q 2 -o eu.triplemining.com:8344 -u xxxxxx -p xxxx -o mint.bitminter.com:8332 -u xxxxx -p xxx -T --syslog   2> STDERR.log

BFGMiner is built on gentoo, with following builtflags.
matze@pucky ~ $ emerge -p -1 --verbose bfgminer

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R   ~] net-misc/bfgminer-3.0.1::bitcoin  USE="adl cpumining examples ncurses opencl sse2 udev ztex (-altivec) -avalon -bitforce -hardened -icarus -modminer -padlock -scrypt -sse2_4way -sse4 -x6500"

I suggest, the miner should switch several times bitween pools until it got connection or exit with a useful error-message.

Oppinions?

Regards Matthias

**Comment by luke-jr** [comment] 2013-06-05 06:38
I believe this should be fixed in the latest git code, soon to become 3.1.0. Please close this bug when you have confirmed it is fixed.

**Comment by add1ct3dd** [comment] 2013-07-25 15:00
I still get this issue and im 3.1.3

Accepted 0d92dc63 OCL 3  pool 1 Diff 0/0Segmentation fault (core dumped)

assuming this is the same thing?

This is all i managed to see, but this happened when I lost internet connection also.

**Comment by luke-jr** [comment] 2013-07-25 18:53
@add1ct3dd Explain why you think your crash has anything to do with this issue?

**Comment by add1ct3dd** [comment] 2013-07-25 19:27
Because all my pools were down (no internet), it had submitted a share of 0 diff (hashing when not connected), and then crashed after. Do you have any other suggestions? 

If you have another thought then please let me know? 

Pure coincedence we both crash at the same time though, unless we have the same failover pool ^^

**Comment by luke-jr** [comment] 2013-07-25 19:29
Please open a new issue for your problem, and preferably include a backtrace..

**Closed as completed by luke-jr** 2013-07-25 19:29 UTC
Labels: bug
