### ISSUE TITLE
Unknown stratum msg: "Method not found"

### ISSUE THREAD

**Issue by Letme** [luke-jr/bfgminer#271] opened 2013-08-30 07:26 UTC
Before I get to detailed reading of code, maybe someone could explain me the below Unknown stratum msg. It probably affects something as I do not think I am doing any mining. Help/advice wanted - I can provide further details if needed (bfgminer version 3.1.4

0            |   0.0/769.6/  0.0kh/s | A:0 R:0+0(none) HW:0/none
OCL 0:       |  ERR /769.3/  0.0kh/s | A:0 R:0+0(none) HW:0/none

 [2013-08-30 09:21:49] Unknown stratum msg: {"error": {"message": "Method not found", "code": -32601, "data": null}, "jsonrpc": "2.0", "id": "txlist21113054859690226509467881
926496231517", "result": null}

**Comment by luke-jr** [comment] 2013-08-30 11:58
It's debug log-level for a reason. It's not a problem.

**Comment by sirmax1** [comment] 2013-12-03 18:28
Hello luke,
I understand it being a debug message and my question is why has it not be fixed yet in v3.8.0
my debug is off and verbose is on and i am still seeing that same message repeating you have above there.

**Comment by luke-jr** [comment] 2013-12-03 18:58
It's not a bug. It's a limitation of your server.

**Comment by luke-jr** [comment] 2013-12-03 19:03
Ah, I did find a bug: this is being logged at a higher level than it should be...

**Comment by luke-jr** [comment] 2013-12-03 19:29
Fixed in 99cd7ed

**Closed as completed by luke-jr** 2013-12-03 19:29 UTC
Labels: invalid
